// Firebase Configuration
// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
// This file is generated by build-config.js from .env
//
// SECURITY NOTE:
// Firebase web API keys are designed to be public (client-side keys).
// Your app's security is enforced through:
// 1. ✅ Firebase Security Rules (Firestore/Storage/Database)
// 2. ✅ Authorized domains in Firebase Console
// 3. ✅ Optional: Firebase App Check for additional protection
//
// These client-side keys are NOT secret. They identify your Firebase project
// and are meant to be included in client applications.
//
// Learn more: https://firebase.google.com/docs/projects/api-keys

const firebaseConfig = {
    apiKey: "AIzaSyDVZh7wLZeFXpoxIqwKFtC8KsYj9zF6lBM",
    authDomain: "eisenhauer-matrix.firebaseapp.com",
    projectId: "eisenhauer-matrix",
    storageBucket: "eisenhauer-matrix.firebasestorage.app",
    messagingSenderId: "174175941071",
    appId: "1:174175941071:web:80d5a25ed700b99809e2ba",
    measurementId: "G-VY3618D2RT"
};

// Firebase initialisieren
firebase.initializeApp(firebaseConfig);

// Firebase Services
const auth = firebase.auth();
const db = firebase.firestore();

// Auth Provider
const googleProvider = new firebase.auth.GoogleAuthProvider();
googleProvider.setCustomParameters({
    prompt: 'select_account'
});

const appleProvider = new firebase.auth.OAuthProvider('apple.com');

// Optional: Offline-Persistenz aktivieren
db.enablePersistence()
    .catch((err) => {
        if (err.code == 'failed-precondition') {
            console.log('Persistence can only be enabled in one tab at a time.');
        } else if (err.code == 'unimplemented') {
            console.log('The current browser does not support persistence.');
        }
    });
